In [28]:
%env OE_LICENSE=/Users/alexpayne/oe_license.txt

env: OE_LICENSE=/Users/alexpayne/oe_license.txt


In [29]:
from openeye import oechem
from openeye import oedepict
from sklearn.cluster import KMeans
import numpy as np
import importlib
from covid_moonshot_ml.docking import docking as d
from covid_moonshot_ml import schema
from covid_moonshot_ml.datasets import utils

In [30]:
importlib.reload(d)
importlib.reload(schema)
importlib.reload(utils)

<module 'covid_moonshot_ml.datasets.utils' from '/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/covid_moonshot_ml/datasets/utils.py'>

# Exploring kmeans clustering

In [31]:
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])

In [32]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [33]:
kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [34]:
kmeans.predict([[0,0], [10,0]])

array([1, 0], dtype=int32)

In [35]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])

# Load in MCSS pickle

In [36]:
import pickle as pkl

In [37]:
pickle_path = "/Volumes/Rohirrim/local_test/chemiinformatics/mcs_sort_index.pkl"

In [38]:
with open(pickle_path, 'rb') as f:
    data = pkl.load(f)

In [39]:
len(data[0])

582

In [40]:
len(data[1])

220

In [41]:
len(data[2])

582

In [42]:
len(data[2][0])

220

In [43]:
582-220

362

In [44]:
data[2][0]

array([ 84,   0,   2,   3,   4,   7,   9,  10,  11,  13,  14,  15,  19,
        21,  22,  23,  24,  25,  28,  29,  30,  31,  32,  34,  35,  36,
        37,  38,  39,  42,  43,  44,  45,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        67,  68,  69,  73,  74,  75,  77,  78,  79,  80,  81,  82,  83,
        87,  88,  89,  90,  92,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 124, 125, 126, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149, 150, 152, 153, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 165, 166, 167, 168, 169, 170, 171, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 190,
       191, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 217, 218,  3

In [45]:
data[2][110]

array([ 58,  77, 140, 141, 130, 133, 134, 135, 136, 153, 158, 159, 177,
         0,   7,   8,  15,  33,  86,  87,  89,  90,  91,  94, 123, 124,
       125, 131, 132, 137, 138, 139, 142, 146, 151, 162, 168, 169, 170,
       171, 172, 176, 178, 179, 180, 187, 188, 189, 190, 191, 194, 196,
       197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 211, 212, 213,
       214, 218,   1,   2,   3,   4,   5,   6,   9,  10,  11,  12,  13,
        14,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  78,  79,  80,  81,  82,
        83,  84,  85,  88,  92,  93,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 126, 127, 128, 12

In [97]:
X = data[2]

In [99]:
kmeans = KMeans(n_clusters=10, random_state=0).fit(X)

In [100]:
kmeans.labels_

array([7, 7, 7, 3, 3, 3, 3, 5, 5, 8, 1, 3, 6, 5, 5, 7, 5, 6, 6, 6, 4, 8,
       9, 3, 3, 9, 3, 3, 3, 6, 9, 3, 9, 4, 4, 1, 1, 1, 6, 3, 5, 3, 3, 3,
       3, 8, 1, 1, 8, 9, 9, 9, 9, 1, 7, 1, 1, 9, 1, 1, 7, 7, 1, 7, 9, 4,
       4, 4, 4, 4, 4, 4, 4, 6, 1, 1, 8, 1, 8, 4, 4, 4, 4, 1, 4, 4, 1, 1,
       3, 3, 3, 0, 8, 9, 5, 5, 1, 8, 3, 5, 8, 8, 8, 8, 8, 5, 8, 8, 8, 8,
       3, 1, 8, 3, 6, 8, 8, 8, 8, 3, 9, 8, 3, 4, 1, 9, 4, 2, 3, 1, 1, 1,
       1, 7, 4, 1, 4, 4, 9, 4, 8, 1, 2, 9, 9, 9, 8, 6, 8, 6, 2, 1, 1, 1,
       1, 1, 1, 1, 2, 8, 9, 1, 7, 9, 9, 1, 7, 2, 2, 0, 1, 1, 1, 2, 2, 4,
       9, 4, 4, 4, 8, 4, 9, 9, 9, 3, 8, 8, 2, 2, 2, 1, 0, 4, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 9, 8, 8, 3, 1, 1, 2, 3, 3, 3, 6, 3, 8, 8, 1, 1,
       1, 1, 1, 1, 1, 1, 8, 6, 8, 3, 8, 8, 7, 7, 3, 3, 3, 4, 8, 3, 4, 6,
       8, 9, 2, 0, 8, 2, 1, 2, 2, 0, 1, 4, 4, 4, 4, 4, 4, 4, 0, 2, 4, 0,
       5, 2, 2, 9, 9, 9, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 2, 9, 1, 0, 0,
       9, 9, 9, 9, 8, 3, 8, 3, 8, 3, 9, 1, 7, 9, 9,

In [101]:
kmeans.cluster_centers_

array([[ 52.07407407,  69.59259259,  64.        , ..., 187.92592593,
        169.40740741, 190.48148148],
       [143.17857143, 133.3452381 ,  56.46428571, ..., 212.97619048,
        209.86904762, 216.01190476],
       [ 98.90721649,  87.27835052, 111.15463918, ..., 139.98969072,
        169.28865979,  26.42268041],
       ...,
       [ 43.48      ,  35.32      ,  33.08      , ..., 163.44      ,
        163.48      , 176.52      ],
       [ 66.59782609,  69.76086957,  87.82608696, ..., 206.92391304,
        199.40217391, 206.2826087 ],
       [ 49.98630137,  29.82191781,  74.53424658, ..., 145.45205479,
        197.68493151, 203.4109589 ]])

In [50]:
cluster_1 = np.array(data[0])[kmeans.labels_==1]

In [102]:
cmpd_to_label_dict = {data[0][i]: kmeans.labels_[i] for i in range(len(data[0]))}

In [103]:
cmpd_to_label_dict

{'AGN-NEW-891393a6-1': 7,
 'CHR-SOS-7098f804-10': 7,
 'CHR-SOS-7098f804-14': 7,
 'DAR-DIA-fb20be43-6': 3,
 'DAR-DIA-fb20be43-7': 3,
 'DUN-NEW-f8ce3686-23': 3,
 'DUN-NEW-f8ce3686-24': 3,
 'GAB-REV-70cc3ca5-8': 5,
 'GIA-UNK-a79af1bc-1': 5,
 'JOH-MSK-a63bdd1d-4': 8,
 'JOR-UNI-2fc98d0b-12': 1,
 'JUA-UNI-bc099708-2': 3,
 'JUA-UNI-bc099708-3': 6,
 'LON-WEI-8f408cad-1': 5,
 'LON-WEI-8f408cad-2': 5,
 'LON-WEI-8f408cad-3': 7,
 'LON-WEI-8f408cad-4': 5,
 'LON-WEI-8f408cad-5': 6,
 'LON-WEI-8f408cad-7': 6,
 'MAK-UNK-af83ef51-6': 6,
 'MAT-POS-916a2c5a-2': 4,
 'MED-COV-4280ac29-12': 8,
 'MED-COV-4280ac29-15': 9,
 'MED-COV-4280ac29-25': 3,
 'MED-COV-4280ac29-31': 3,
 'MED-COV-4280ac29-33': 9,
 'MED-COV-4280ac29-37': 3,
 'MIH-UNI-e573136b-5': 3,
 'NEH-REV-107bcf72-5': 3,
 'NIR-THE-0d6461ce-8': 6,
 'PAU-UNI-8cdd41c7-1': 9,
 'SIM-SYN-f15aaa3a-1': 3,
 'STU-CHA-6cae54d3-1': 9,
 'STU-CHA-83dacf15-1': 4,
 'TAM-UNI-d1c3dd9f-5': 4,
 'TRY-UNI-714a760b-19': 1,
 'TRY-UNI-714a760b-3': 1,
 'TRY-UNI-714a760b-6': 1,


In [53]:
cluster_0 = np.array(data[0])[kmeans.labels_==0]

## get smiles for each molecule

In [54]:
cmpd_tracker = "/Users/alexpayne/Scientific_Projects/mers-drug-discovery/Mpro_compound_tracker_csv.csv"
xtal_compounds = d.parse_xtal(cmpd_tracker, "")

In [55]:
len(xtal_compounds)

220

## load cmpd_to_frag

In [56]:
import yaml

In [57]:
with open("../data/cmpd_to_frag.yaml") as f:
    cmpd_to_frag_dict = yaml.safe_load(f)

In [58]:
frag_to_cmpd = {frag: cmpd for cmpd, frag in cmpd_to_frag_dict.items()}

In [59]:
for xtal in xtal_compounds:
    xtal.compound_id=frag_to_cmpd[xtal.dataset]

In [60]:
xtal_compounds

[CrystalCompoundData(smiles='ClC=1C=CC=C(CC(=O)NC=2C=NC=C3C=CC=CC23)C1', compound_id='ADA-UCB-6c2cb422-1', dataset='Mpro-P2005', str_fn=None, sdf_fn=None),
 CrystalCompoundData(smiles='ClC=1C=CC=2CN(CC3(CCCN(C3=O)C=4C=NC=C5C=CC=CC45)C2C1)S(=O)(=O)CC6(CC6)C#N', compound_id='ALP-POS-133e7cd9-2', dataset='Mpro-P3074', str_fn=None, sdf_fn=None),
 CrystalCompoundData(smiles='CC1(CNS(=O)(=O)C=2C=CC(Cl)=CC21)C(=O)NC=3C=NC=C4C=CC=CC34', compound_id='ALP-POS-1cbc2fae-1', dataset='Mpro-P2036', str_fn=None, sdf_fn=None),
 CrystalCompoundData(smiles='CCC1(CNS(=O)(=O)C=2C=CC(Cl)=CC21)C(=O)NC=3C=NC=C4C=CC=CC34', compound_id='ALP-POS-1cbc2fae-2', dataset='Mpro-P2381', str_fn=None, sdf_fn=None),
 CrystalCompoundData(smiles='ClC=1C=CC2=C(C1)C(CNS2(=O)=O)C(=O)NC=3C=NC=C4CCCCC34', compound_id='ALP-POS-4483ae88-4', dataset='Mpro-P2415', str_fn=None, sdf_fn=None),
 CrystalCompoundData(smiles='ClC=1C=CC=2OCCC3(CCN(C3=O)C=4C=NC=C5C=CC=CC45)C2C1', compound_id='ALP-POS-477dc5b7-4', dataset='Mpro-P2197', str_fn

In [61]:
frag_data = utils.parse_fragalysis_data(cmpd_tracker, "")

File Mpro-x1311_0A/Mpro-x1311_0A.sdf not found...
File Mpro-x1382_0A/Mpro-x1382_0A.sdf not found...
File Mpro-x1392_0A/Mpro-x1392_0A.sdf not found...
File Mpro-x1402_0A/Mpro-x1402_0A.sdf not found...
File Mpro-x1412_0A/Mpro-x1412_0A.sdf not found...
File Mpro-x1425_0A/Mpro-x1425_0A.sdf not found...
File Mpro-x1334_0A/Mpro-x1334_0A.sdf not found...
File Mpro-x1478_0A/Mpro-x1478_0A.sdf not found...
File Mpro-x1493_0A/Mpro-x1493_0A.sdf not found...
File Mpro-x0887_0A/Mpro-x0887_0A.sdf not found...
File Mpro-x1187_0A/Mpro-x1187_0A.sdf not found...
File Mpro-x1012_0A/Mpro-x1012_0A.sdf not found...
File Mpro-x0390_0A/Mpro-x0390_0A.sdf not found...
File Mpro-x0425_0A/Mpro-x0425_0A.sdf not found...
File Mpro-x0398_0A/Mpro-x0398_0A.sdf not found...
File Mpro-x0669_0A/Mpro-x0669_0A.sdf not found...
File Mpro-x1163_0A/Mpro-x1163_0A.sdf not found...
File Mpro-x0177_0A/Mpro-x0177_0A.sdf not found...
File Mpro-x0194_0A/Mpro-x0194_0A.sdf not found...
File Mpro-x1226_0A/Mpro-x1226_0A.sdf not found...


In [62]:
len(frag_data)

4484

In [63]:
set(frag_data)

{'MF-Crude-F11',
 'FRA-BIO-8bf1eac9-9',
 'MAT-POS-29385cc1-2',
 'NAU-LAT-445f63e5-7',
 'SER-UNI-985a0e14-4',
 'POB0096',
 'MAT-POS-90fd5f68-3',
 'RAL-THA-2d450e86-8',
 'LOR-NOR-c954e7ad-1',
 'MAT-POS-90fd5f68-13',
 'BEN-DND-76ad4ac9-14',
 'RUT-UNI-630c5802-20',
 'IAN-BAS-5394d4c4-1',
 'JOH-UNI-9b01dc72-1',
 'MAT-POS-dd3ad2b5-2',
 'DUN-NEW-f8ce3686-14',
 'UNK-UNK-2ede4078-72',
 'Compound39',
 'Cov_HetLib 099',
 'Z45705015',
 'MAT-POS-8293a91a-5',
 'JUA-UNI-a9dfaed1-2',
 'BAR-COM-4e090d3a-29',
 'MAT-POS-bfefc3ea-3',
 'AAR-POS-8a4e0f60-10',
 'BEN-DND-93268d01-4',
 'EDJ-MED-41558c53-6',
 'MAT-POS-ea426761-13',
 'JAG-UCB-52b62a6f-7',
 'NCL-00024773',
 'ALP-POS-ddb41b15-1',
 'Z1722836661',
 'Z2472938267',
 'Z5551316242',
 'Z2856434910',
 'MIK-UNK-122557fa',
 'UNK-UNK-2ede4078-60',
 'Compound106',
 'EDJ-MED-d08626de-5',
 'EDJ-MED-dac03e7f-2',
 'Z1134990241',
 'DRA-CSI-7ec17797-18',
 'LON-WEI-8f408cad-8',
 'MAT-POS-e75f6e44-12',
 'MAT-POS-61f37a1a-4',
 'Compound99',
 'STU-CHA-83dacf15-1',
 'MF

In [64]:
cmpd_info = [frag_data.get(cmpd_id) for cmpd_id in data[0]]

In [65]:
sum(np.array(cmpd_info) != None)

546

In [66]:
len(data[0])

582

In [67]:
mapped_data = {}
for i in range(len(data[0])):
    cmpd_data = cmpd_info[i]
    if cmpd_data:
        mapped_data[cmpd_data.compound_id] = (cmpd_data, data[2][i])

In [68]:
len(mapped_data)

546

In [69]:
mapped_data["AAR-POS-5507155c-1"]

(CrystalCompoundData(smiles='Cl.Cl.CS(=O)(=O)C=1C=CC(=CC1)N2CCNCC2', compound_id='AAR-POS-5507155c-1', dataset='Mpro-x2193', str_fn=None, sdf_fn=None),
 array([ 85,  89,  90,  30,  51,  69,  97,  65,   0,   1,   2,   3,   4,
          5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
         18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  31,
         32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
         45,  46,  47,  48,  49,  50,  52,  53,  54,  55,  56,  57,  58,
         59,  60,  61,  62,  63,  64,  66,  67,  68,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  86,  87,
         88,  91,  92,  93,  94,  95,  96,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 15

In [70]:
key_filter = [key for key in frag_data.keys() if "BEN-DND" in key]

In [71]:
key_filter.sort()
key_filter

['BEN-DND-031a96cc-8',
 'BEN-DND-03406596-11',
 'BEN-DND-03406596-12',
 'BEN-DND-03406596-8',
 'BEN-DND-03ad4429-1',
 'BEN-DND-03ad4429-2',
 'BEN-DND-03ad4429-4',
 'BEN-DND-03ad4429-5',
 'BEN-DND-03ad4429-6',
 'BEN-DND-03ad4429-8',
 'BEN-DND-1e24cf73-1',
 'BEN-DND-362d364a-10',
 'BEN-DND-4f474d93-1',
 'BEN-DND-4f474d93-2',
 'BEN-DND-61647d40-12',
 'BEN-DND-61647d40-13',
 'BEN-DND-61647d40-14',
 'BEN-DND-61647d40-18',
 'BEN-DND-61647d40-8',
 'BEN-DND-76ad4ac9-10',
 'BEN-DND-76ad4ac9-11',
 'BEN-DND-76ad4ac9-12',
 'BEN-DND-76ad4ac9-13',
 'BEN-DND-76ad4ac9-14',
 'BEN-DND-76ad4ac9-9',
 'BEN-DND-7e92b6ca-1',
 'BEN-DND-7e92b6ca-10',
 'BEN-DND-7e92b6ca-11',
 'BEN-DND-7e92b6ca-12',
 'BEN-DND-7e92b6ca-13',
 'BEN-DND-7e92b6ca-14',
 'BEN-DND-7e92b6ca-16',
 'BEN-DND-7e92b6ca-2',
 'BEN-DND-7e92b6ca-3',
 'BEN-DND-7e92b6ca-4',
 'BEN-DND-7e92b6ca-5',
 'BEN-DND-7e92b6ca-7',
 'BEN-DND-7e92b6ca-8',
 'BEN-DND-93268d01-1',
 'BEN-DND-93268d01-10',
 'BEN-DND-93268d01-11',
 'BEN-DND-93268d01-13',
 'BEN-DND-932

In [72]:
data[0]

['AGN-NEW-891393a6-1',
 'CHR-SOS-7098f804-10',
 'CHR-SOS-7098f804-14',
 'DAR-DIA-fb20be43-6',
 'DAR-DIA-fb20be43-7',
 'DUN-NEW-f8ce3686-23',
 'DUN-NEW-f8ce3686-24',
 'GAB-REV-70cc3ca5-8',
 'GIA-UNK-a79af1bc-1',
 'JOH-MSK-a63bdd1d-4',
 'JOR-UNI-2fc98d0b-12',
 'JUA-UNI-bc099708-2',
 'JUA-UNI-bc099708-3',
 'LON-WEI-8f408cad-1',
 'LON-WEI-8f408cad-2',
 'LON-WEI-8f408cad-3',
 'LON-WEI-8f408cad-4',
 'LON-WEI-8f408cad-5',
 'LON-WEI-8f408cad-7',
 'MAK-UNK-af83ef51-6',
 'MAT-POS-916a2c5a-2',
 'MED-COV-4280ac29-12',
 'MED-COV-4280ac29-15',
 'MED-COV-4280ac29-25',
 'MED-COV-4280ac29-31',
 'MED-COV-4280ac29-33',
 'MED-COV-4280ac29-37',
 'MIH-UNI-e573136b-5',
 'NEH-REV-107bcf72-5',
 'NIR-THE-0d6461ce-8',
 'PAU-UNI-8cdd41c7-1',
 'SIM-SYN-f15aaa3a-1',
 'STU-CHA-6cae54d3-1',
 'STU-CHA-83dacf15-1',
 'TAM-UNI-d1c3dd9f-5',
 'TRY-UNI-714a760b-19',
 'TRY-UNI-714a760b-3',
 'TRY-UNI-714a760b-6',
 'WAR-XCH-79d12f6e-4',
 'WAR-XCH-79d12f6e-6',
 'WAR-XCH-b0339bbe-19',
 'AAR-POS-8a4e0f60-7',
 'JUA-UNI-a9dfaed1-2'

## write out first 10 structures for each cluster

In [89]:
cmpd_id = cluster_0[0]
smiles = mapped_data[cmpd_id][0].smiles

In [90]:
mol = oechem.OEGraphMol()

In [91]:
oechem.OESmilesToMol(mol, smiles)

True

In [92]:
mol

<oechem.OEGraphMol; proxy of <Swig Object of type 'OEGraphMolWrapper *' at 0x7fab2a2ea2a0> >

In [93]:
from covid_moonshot_ml.data import openeye as oe

In [110]:
cluster = 7
for i in range(10):
    cmpd_id = np.array(data[0])[kmeans.labels_ == cluster][i]
    smiles = mapped_data[cmpd_id][0].smiles
    mol = oechem.OEGraphMol()
    oechem.OESmilesToMol(mol, smiles)
    oe.write_openeye_ligand(mol, out_fn=f"/Volumes/Rohirrim/local_test/chemiinformatics/cluster{cluster}_{cmpd_id}.png")

In [ ]:
oechem.OEMCS

# Play with options for MCSS based clustering

In [ ]:
cmpd_id = np.array(data[0])[kmeans.labels_ == cluster][0]
smiles = mapped_data[cmpd_id][0].smiles
mol1 = oechem.OEGraphMol()
oechem.OESmilesToMol(mol1, smiles)