In [50]:
import mdtraj as md
import os

In [5]:
mobile_sdf_fn = "kinoml_OEDockingFeaturizer_MPRO_Mpro-P0764_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_1_1.sdf"
ref_sdf_fn = "Mpro-P2005_0A/Mpro-P2005_0A.sdf"

mobile_pdb_fn = "kinoml_OEDockingFeaturizer_MPRO_Mpro-P0098_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_3.pdb"
ref_pdb_fn = "Mpro-P2005_0A/Mpro-P2005_0A_bound.pdb"

In [6]:
sdf_dir = "/Users/alexpayne/Scientific_Projects/sdfs/"

In [9]:
ref = md.load_pdb(os.path.join(sdf_dir, ref_pdb_fn))

In [18]:
ref_lig = ref.atom_slice(ref.topology.select("resn LIG"))

In [19]:
ref_lig

<mdtraj.Trajectory with 1 frames, 21 atoms, 1 residues, without unitcells at 0x7ff6fbf75af0>

In [22]:
for atom in ref_lig.topology.atoms:
    print(atom)

LIG410-O
LIG410-C6
LIG410-C5
LIG410-C4
LIG410-C3
LIG410-C2
LIG410-C1
LIG410-C16
LIG410-C
LIG410-CL
LIG410-N
LIG410-C7
LIG410-C15
LIG410-C14
LIG410-C13
LIG410-C12
LIG410-C11
LIG410-C10
LIG410-C9
LIG410-N1
LIG410-C8


In [23]:
ref_lig.xyz

array([[[ 0.8902,  0.0837,  2.1288],
        [ 0.8367, -0.0234,  2.1579],
        [ 0.8954, -0.1164,  2.2625],
        [ 1.0367, -0.0797,  2.302 ],
        [ 1.0609,  0.0104,  2.4051],
        [ 1.1898,  0.0541,  2.4324],
        [ 1.2965,  0.0085,  2.3567],
        [ 1.1446, -0.1291,  2.2294],
        [ 1.2722, -0.0837,  2.2568],
        [ 1.4056, -0.1444,  2.1621],
        [ 0.7226, -0.0691,  2.1005],
        [ 0.6474, -0.0105,  1.9964],
        [ 0.5351,  0.0715,  2.0309],
        [ 0.4871,  0.088 ,  2.1635],
        [ 0.3817,  0.1709,  2.1903],
        [ 0.3195,  0.2418,  2.0882],
        [ 0.3613,  0.2285,  1.9588],
        [ 0.4692,  0.1423,  1.9263],
        [ 0.5166,  0.1236,  1.794 ],
        [ 0.619 ,  0.0456,  1.7615],
        [ 0.6819, -0.0187,  1.8612]]], dtype=float32)

In [24]:
mobile = md.load_pdb(os.path.join(sdf_dir, mobile_pdb_fn))

In [28]:
mobile.topology.select("resn LIG")

array([4613, 4614, 4615, 4616, 4617, 4618, 4619, 4620, 4621, 4622, 4623,
       4624, 4625, 4626, 4627, 4628, 4629, 4630, 4631, 4632, 4633, 4634,
       4635, 4636, 4637, 4638, 4639, 4640, 4641, 4642, 4643, 4644, 4645,
       4646])

In [49]:
mobile_lig = mobile.atom_slice(mobile.topology.select("resn LIG and not symbol H"))

In [50]:
for atom in mobile_lig.topology.atoms:
    print(atom)
    

LIG303-C1
LIG303-C2
LIG303-C3
LIG303-C4
LIG303-C5
LIG303-C6
LIG303-C7
LIG303-C8
LIG303-C9
LIG303-C10
LIG303-C11
LIG303-C12
LIG303-C13
LIG303-C14
LIG303-C15
LIG303-C16
LIG303-C17
LIG303-N18
LIG303-N19
LIG303-O20
LIG303-CL21


In [51]:
mobile2 = md.load_pdb(os.path.join(sdf_dir, 
                                   "kinoml_OEDockingFeaturizer_MPRO_Mpro-P2005_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex.pdb"))

In [60]:
mobile2_lig = mobile2.atom_slice(mobile2.topology.select("resn LIG and not symbol H"))

In [61]:
for atom in mobile2_lig.topology.atoms:
    print(atom)

LIG307-C1
LIG307-C2
LIG307-C3
LIG307-C4
LIG307-C5
LIG307-C6
LIG307-C7
LIG307-C8
LIG307-C9
LIG307-C10
LIG307-C11
LIG307-C12
LIG307-C13
LIG307-C14
LIG307-C15
LIG307-C16
LIG307-C17
LIG307-N18
LIG307-N19
LIG307-O20
LIG307-CL21


In [66]:
md.rmsd(mobile2_lig, mobile_lig, precentered=True)

/var/folders/cf/d42qwdmd5_g5s63r3g_vgx2c0000gn/T/ipykernel_7254/3593535001.py:1: RuntimeWarning: in rmsd(), precentered is ignored when atom_indices != None
  md.rmsd(mobile2_lig, mobile_lig, precentered=True)


array([0.19073766], dtype=float32)

In [69]:
md.rmsd(ref_lig, mobile_lig, precentered=True)

/var/folders/cf/d42qwdmd5_g5s63r3g_vgx2c0000gn/T/ipykernel_7254/4275661744.py:1: RuntimeWarning: in rmsd(), precentered is ignored when atom_indices != None
  md.rmsd(ref_lig, mobile_lig, precentered=True)


array([0.51450497], dtype=float32)

In [70]:
help(md.rmsd)

Help on built-in function rmsd in module mdtraj._rmsd:

rmsd(...)
    rmsd(target, reference, frame=0, atom_indices=None, parallel=True, precentered=False)
    
    Compute RMSD of all conformations in target to a reference conformation.
    Note, this will center the conformations in place.
    
    Parameters
    ----------
    target : md.Trajectory
        For each conformation in this trajectory, compute the RMSD to
        a particular 'reference' conformation in another trajectory
        object.
    reference : md.Trajectory
        The object containing the reference conformation to measure distances
        to.
    frame : int, default=0
        The index of the conformation in `reference` to measure
        distances to.
    atom_indices : array_like, or None
        The indices of the atoms to use in the RMSD calculation. If not
        supplied, all atoms will be used.
    ref_atom_indices : array_like, or None
        Use these indices for the reference trajectory. If not

In [71]:
mobile_paths = [path for path in os.listdir("/Users/alexpayne/Scientific_Projects/sdfs/") if path[-3:] == "pdb"]

In [72]:
mobile_paths

['kinoml_OEDockingFeaturizer_MPRO_Mpro-P0098_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_3.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2176_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_4.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2185_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_9.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_0B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_0.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_6.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P0764_0B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_1.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_1B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_0.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P0764_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_1.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_6.pdb',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_1A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_0.pdb',
 'kinoml_OEDockingFeaturizer_M

In [79]:
fake_ref_lig = mobile2_lig
for path in mobile_paths:
    print(path)
    mobile = md.load_pdb(os.path.join(sdf_dir, path))
    mobile_lig = mobile.atom_slice(mobile.topology.select("resn LIG and not symbol H"))
    rmsd = md.rmsd(fake_ref_lig, mobile_lig)[0] * 10
    print(md.rmsd(fake_ref_lig, mobile_lig, precentered=True)[0])
    print(f"{rmsd:.2f}")

kinoml_OEDockingFeaturizer_MPRO_Mpro-P0098_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_3.pdb
0.053289063
0.53
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2176_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_4.pdb


/var/folders/cf/d42qwdmd5_g5s63r3g_vgx2c0000gn/T/ipykernel_7254/2780060498.py:7: RuntimeWarning: in rmsd(), precentered is ignored when atom_indices != None
  print(md.rmsd(fake_ref_lig, mobile_lig, precentered=True)[0])


0.15666892
1.57
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2185_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_9.pdb
0.011323594
0.11
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_0B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_0.pdb
0.010689213
0.11
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_6.pdb
0.008861105
0.09
kinoml_OEDockingFeaturizer_MPRO_Mpro-P0764_0B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_1.pdb
0.15046376
1.50
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_1B_seqres_chainB_ADA-UCB-6c2cb422-1_complex_0.pdb
0.010689213
0.11
kinoml_OEDockingFeaturizer_MPRO_Mpro-P0764_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_1.pdb
0.14865035
1.49
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_6.pdb
0.0055631828
0.06
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_1A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_0.pdb
0.009602668
0.10
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_0.pdb
0.009602668


In [80]:
import numpy as np

In [81]:
np.linalg.norm(ref_lig.xyz[0], ref_lig.xyz[0])

/Users/alexpayne/opt/anaconda3/envs/mers-docking2/lib/python3.8/site-packages/numpy/linalg/linalg.py:2517: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  (ord in ('f', 'fro') and ndim == 2) or


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [46]:
def cal_rmsd_numpy(coord_1, coord_2):
    rmsd = np.sqrt((((coord_1 - coord_2)** 2)*3).mean())
    return rmsd

In [84]:
cal_rmsd_numpy(ref_lig.xyz[0], mobile_lig.xyz[0])

0.54625016

In [85]:
path

'kinoml_OEDockingFeaturizer_MPRO_Mpro-P0394_0A_seqres_chainA_ADA-UCB-6c2cb422-1_complex_2.pdb'

In [95]:
xyz1 = ref_lig.xyz[0]*10
xyz2 = mobile_lig.xyz[0]*10

In [96]:
xyz1

array([[ 0.9162859 ,  0.5541905 ,  0.06642751],
       [ 0.38128603, -0.5168095 ,  0.35742936],
       [ 0.96828556, -1.4468095 ,  1.4034289 ],
       [ 2.381286  , -1.0798095 ,  1.7984289 ],
       [ 2.6232853 , -0.1788095 ,  2.8294296 ],
       [ 3.9122858 ,  0.25819048,  3.1024284 ],
       [ 4.9792852 , -0.1978095 ,  2.345428  ],
       [ 3.460286  , -1.5738094 ,  1.0724276 ],
       [ 4.7362857 , -1.1198095 ,  1.3464278 ],
       [ 6.0702853 , -1.7268095 ,  0.39942917],
       [-0.7597145 , -0.9738095 , -0.21657059],
       [-1.511714  , -0.38780951, -1.2575716 ],
       [-2.6347146 ,  0.43219054, -0.91257155],
       [-3.1147144 ,  0.5971905 ,  0.4134291 ],
       [-4.1687145 ,  1.4261904 ,  0.6814283 ],
       [-4.7907143 ,  2.1351905 , -0.33957067],
       [-4.3727145 ,  2.0021904 , -1.633572  ],
       [-3.2937145 ,  1.1401905 , -1.9585711 ],
       [-2.8197143 ,  0.95319045, -3.2815714 ],
       [-1.795714  ,  0.1731905 , -3.6065717 ],
       [-1.1667141 , -0.4698095 , -2.609

In [97]:
xyz2

array([[ 3.7079523 ,  3.3253808 ,  2.0664282 ],
       [ 2.3149524 ,  3.3563805 ,  2.0444293 ],
       [-3.0810478 , -2.0216188 , -2.9615717 ],
       [ 4.3859525 ,  2.165381  ,  1.6944284 ],
       [ 1.5949522 ,  2.2273812 ,  1.6504283 ],
       [-2.4120476 , -1.9186189 , -1.7425709 ],
       [-4.169048  , -1.191619  , -3.2325716 ],
       [-3.9190474 , -0.15661903, -1.0635715 ],
       [ 4.2989526 , -0.163619  ,  0.9124298 ],
       [ 2.298952  , -1.219619  ,  0.5124278 ],
       [ 3.6719522 ,  1.023381  ,  1.2954278 ],
       [ 2.261952  ,  1.0513809 ,  1.2714286 ],
       [-2.8310475 , -0.98561907, -0.79357195],
       [ 1.5689527 , -0.09661905,  0.87142897],
       [-4.5880475 , -0.25861895, -2.2835712 ],
       [-0.6340476 , -1.238619  ,  0.4374285 ],
       [-2.1080477 , -0.876619  ,  0.52342844],
       [ 3.6479518 , -1.282619  ,  0.52342844],
       [ 0.1729522 , -0.15661903,  0.8184285 ],
       [-0.2520474 , -2.346619  ,  0.0734277 ],
       [-5.9310474 ,  0.76438093, -2.617

In [98]:
xyz1-xyz2

array([[-2.79166651e+00, -2.77119017e+00, -2.00000072e+00],
       [-1.93366635e+00, -3.87318993e+00, -1.68699992e+00],
       [ 4.04933357e+00,  5.74809313e-01,  4.36500072e+00],
       [-2.00466657e+00, -3.24519062e+00,  1.04000449e-01],
       [ 1.02833307e+00, -2.40619063e+00,  1.17900133e+00],
       [ 6.32433319e+00,  2.17680931e+00,  4.84499931e+00],
       [ 9.14833260e+00,  9.93809521e-01,  5.57799959e+00],
       [ 7.37933350e+00, -1.41719031e+00,  2.13599920e+00],
       [ 4.37333107e-01, -9.56190526e-01,  4.33997989e-01],
       [ 3.77133322e+00, -5.07190466e-01, -1.12998635e-01],
       [-4.43166685e+00, -1.99719048e+00, -1.51199841e+00],
       [-3.77366590e+00, -1.43919039e+00, -2.52900028e+00],
       [ 1.96332932e-01,  1.41780961e+00, -1.18999600e-01],
       [-4.68366718e+00,  6.93809569e-01, -4.57999855e-01],
       [ 4.19332981e-01,  1.68480933e+00,  2.96499968e+00],
       [-4.15666676e+00,  3.37380934e+00, -7.76999176e-01],
       [-2.26466680e+00,  2.87880945e+00

In [100]:
((xyz1-xyz2)**2).mean()

9.946311

In [102]:
np.sqrt((((xyz1-xyz2)**2)*3).mean())

5.4625025

# OpenEYE

In [9]:
from covid_moonshot_ml.data.openeye import load_openeye_sdf
# print(f"Loading rmsd calc on {sdf_path} compared to {ref_path}")
mobile_sdf = "/Users/alexpayne/Scientific_Projects/sdfs/kinoml_OEDockingFeaturizer_MPRO_Mpro-P0098_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_3.sdf"
mobile = load_openeye_sdf(mobile_sdf)
ref = load_openeye_sdf("/Users/alexpayne/Scientific_Projects/sdfs/Mpro-P2005_0A/Mpro-P2005_0A.sdf")

In [13]:
oechem.OECanonicalOrderAtoms(mobile)
oechem.OECanonicalOrderBonds(mobile)

In [14]:
oechem.OECanonicalOrderAtoms(ref)
oechem.OECanonicalOrderBonds(ref)

In [16]:
oechem.OERMSD(ref, mobile)

-1.0

In [17]:
for atom in mobile.GetAtoms():
    print(atom)

21 H
22 H
23 H
24 H
25 H
26 H
27 H
28 H
29 H
30 H
31 H
32 H
33 H
 0 C
 1 C
 2 C
 3 C
 4 C
 5 C
 6 C
 7 C
 8 C
 9 C
10 C
11 C
12 C
13 C
14 C
15 C
16 C
17 N
18 N
19 O
20Cl


In [21]:
for atom in ref.GetAtoms():
    print(atom)

15 C
14 C
 5 C
16 C
13 C
 4 C
 6 C
 7 C
18 C
20 C
 2 C
 3 C
 8 C
17 C
12 C
11 C
 1 C
19 N
10 N
 0 O
 9Cl


In [34]:
import numpy as np

In [38]:
ref_xyz = np.array(list(ref.GetCoords().values()))

In [39]:
ref_xyz

array([[ 3.19499993,  2.41799998, 20.88199997],
       [ 3.81699991,  1.70899999, 21.90299988],
       [11.89799976,  0.54100001, 24.3239994 ],
       [ 3.61299992,  2.28500009, 19.58799934],
       [ 4.87099981,  0.88      , 21.63500023],
       [10.60900021,  0.104     , 24.0510006 ],
       [12.96500015,  0.085     , 23.56699944],
       [11.4460001 , -1.29100001, 22.29400063],
       [ 5.16599989,  1.23599994, 17.94000053],
       [ 6.81899977, -0.18700001, 18.61199951],
       [ 8.95400047, -1.16400003, 22.625     ],
       [10.36699963, -0.79699999, 23.02000046],
       [12.72200012, -0.83700001, 22.56800079],
       [ 4.69199991,  1.42299998, 19.26300049],
       [ 5.35099983,  0.71499997, 20.30900002],
       [ 6.47399998, -0.105     , 19.9640007 ],
       [ 8.36699963, -0.234     , 21.57900047],
       [ 6.19000006,  0.456     , 17.61499977],
       [ 7.22599983, -0.69099998, 21.00499916],
       [ 8.90200043,  0.83700001, 21.28800011],
       [14.05599976, -1.44400001, 21.621

In [40]:
n_atoms = len(ref_xyz)

In [41]:
mobile_xyz = np.array(list(mobile.GetCoords().values()))

In [43]:
mobile_xyz[-n_atoms:]

array([[ 2.87649989,  2.79029989, 20.58950043],
       [ 3.47280002,  2.18540001, 21.68630028],
       [11.34840012,  0.79149997, 23.95479965],
       [ 3.35349989,  2.52640009, 19.3071003 ],
       [ 4.57329988,  1.35140002, 21.50449944],
       [10.0632    ,  0.32480001, 23.67140007],
       [12.45740032,  0.1895    , 23.36470032],
       [10.99139977, -1.34529996, 22.19490051],
       [ 4.89669991,  1.3197    , 17.84029961],
       [ 6.55420017, -0.0445    , 18.66939926],
       [ 4.44229984,  1.65840006, 19.11319923],
       [ 5.10550022,  1.0891    , 20.21999931],
       [ 9.87320042, -0.7561    , 22.79850006],
       [ 6.23600006,  0.26570001, 19.98649979],
       [12.27330017, -0.87309998, 22.48220062],
       [ 7.9835    , -1.12979996, 21.15089989],
       [ 8.49489975, -1.31470001, 22.56970024],
       [ 5.91069984,  0.4632    , 17.59370041],
       [ 7.00670004, -0.1512    , 21.09600067],
       [ 8.39439964, -1.82360005, 20.22649956],
       [13.64050007, -1.62750006, 21.758

In [44]:
mobile_xyz

array([[ 2.02950001,  3.45309997, 20.73259926],
       [ 3.08789992,  2.35349989, 22.68720055],
       [11.48560047,  1.61520004, 24.64970016],
       [ 2.86190009,  2.99530005, 18.45820045],
       [ 4.98670006,  0.88090003, 22.39319992],
       [ 9.21249962,  0.79759997, 24.15589905],
       [13.45320034,  0.55019999, 23.60720062],
       [10.8579998 , -2.18560004, 21.51799965],
       [ 4.43179989,  1.73080003, 16.94820023],
       [ 7.37559986, -0.69700003, 18.39979935],
       [ 8.49800014, -2.38840008, 22.78980064],
       [ 7.79099989, -0.87910002, 23.29089928],
       [ 6.81090021,  0.3249    , 21.95339966],
       [ 2.87649989,  2.79029989, 20.58950043],
       [ 3.47280002,  2.18540001, 21.68630028],
       [11.34840012,  0.79149997, 23.95479965],
       [ 3.35349989,  2.52640009, 19.3071003 ],
       [ 4.57329988,  1.35140002, 21.50449944],
       [10.0632    ,  0.32480001, 23.67140007],
       [12.45740032,  0.1895    , 23.36470032],
       [10.99139977, -1.34529996, 22.194

In [47]:
cal_rmsd_numpy(ref_xyz, mobile_xyz[-n_atoms:])

2.8140163275089867

## automate

In [48]:
ref_xyz

array([[ 3.19499993,  2.41799998, 20.88199997],
       [ 3.81699991,  1.70899999, 21.90299988],
       [11.89799976,  0.54100001, 24.3239994 ],
       [ 3.61299992,  2.28500009, 19.58799934],
       [ 4.87099981,  0.88      , 21.63500023],
       [10.60900021,  0.104     , 24.0510006 ],
       [12.96500015,  0.085     , 23.56699944],
       [11.4460001 , -1.29100001, 22.29400063],
       [ 5.16599989,  1.23599994, 17.94000053],
       [ 6.81899977, -0.18700001, 18.61199951],
       [ 8.95400047, -1.16400003, 22.625     ],
       [10.36699963, -0.79699999, 23.02000046],
       [12.72200012, -0.83700001, 22.56800079],
       [ 4.69199991,  1.42299998, 19.26300049],
       [ 5.35099983,  0.71499997, 20.30900002],
       [ 6.47399998, -0.105     , 19.9640007 ],
       [ 8.36699963, -0.234     , 21.57900047],
       [ 6.19000006,  0.456     , 17.61499977],
       [ 7.22599983, -0.69099998, 21.00499916],
       [ 8.90200043,  0.83700001, 21.28800011],
       [14.05599976, -1.44400001, 21.621

In [51]:
sdf_paths = [path for path in os.listdir("/Users/alexpayne/Scientific_Projects/sdfs/") if path[-3:] == "sdf"]

In [52]:
sdf_paths

['kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_6.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2218_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_8.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2005_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0B_seqres_chainB_ADA-UCB-6c2cb422-1_ligand_6.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2141_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_5.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_0.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_0B_seqres_chainB_ADA-UCB-6c2cb422-1_ligand_0.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P0098_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_3.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_1B_seqres_chainB_ADA-UCB-6c2cb422-1_ligand_0.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P0764_0B_seqres_chainB_ADA-UCB-6c2cb422-1_ligand_1.sdf',
 'kinoml_OEDockingFeaturizer_MPRO_Mpro-P03

In [59]:
for path in sdf_paths:
    mobile = load_openeye_sdf(os.path.join("/Users/alexpayne/Scientific_Projects/sdfs", path))
    oechem.OECanonicalOrderAtoms(mobile)
    oechem.OECanonicalOrderBonds(mobile)
    mobile_xyz = np.array(list(mobile.GetCoords().values()))
#     print(mobile_xyz)
#     print(ref_xyz)
    print(path)
    print(cal_rmsd_numpy(ref_xyz, mobile_xyz[-n_atoms:]))

kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_6.sdf
2.7235243327615213
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2218_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_8.sdf
2.7404358763811048
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2005_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand.sdf
2.722149069046822
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2210_0B_seqres_chainB_ADA-UCB-6c2cb422-1_ligand_6.sdf
2.7240898272767753
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2141_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_5.sdf
7.251836827896964
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_0.sdf
2.7180261019284693
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_0B_seqres_chainB_ADA-UCB-6c2cb422-1_ligand_0.sdf
2.7219658922411494
kinoml_OEDockingFeaturizer_MPRO_Mpro-P0098_0A_seqres_chainA_ADA-UCB-6c2cb422-1_ligand_3.sdf
2.8140163275089867
kinoml_OEDockingFeaturizer_MPRO_Mpro-P2028_1B_seqres_chainB_ADA-UCB-6c2cb422-1_ligand_0.sdf
2.7219658922411494
kinom